rename "*.3gpx" *.3gp
rename "*.avix" *.avi
rename "*.flvx" *.flv
rename "*.mkvx" *.mkv
rename "*.movx" *.mov
rename "*.mpgx" *.mpg
rename "*.mpegx" *.mpeg
rename "*.mp4x" *.mp4
rename "*.rmvbx" *.rmvb
rename "*.tsx" *.ts
rename "*.webmx" *.webm
rename "*.wmvx" *.wmv
rename "*.gifx" *.gif
rename "*.jpgx" *.jpg
rename "*.jpegx" *.jpeg
rename "*.pngx" *.png
rename "*.webpx" *.webp
